apiVersion: v1
kind: Service
metadata:
  name: medical-text-pipeline
  namespace: medical-pipeline
  labels:
    app: medical-text-pipeline
spec:
  type: ClusterIP
  selector:
    app: medical-text-pipeline
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
